# Generated by Django 4.0.1 on 2022-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('taste', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
